*** Starting uWSGI 2.0.18 (64bit) on [Wed Jul 17 13:23:12 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 17 July 2019 03:11:56
os: Linux-3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017
nodename: w2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mysite
writing pidfile to /root/mysite/uwsgi.pid
detected binary path: /usr/local/python356/bin/uwsgi
setuid() to 997
chdir() to /root/mysite
your processes number limit is 3818
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
Python version: 3.6.5 (default, Jul 17 2019, 10:07:53)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Python main interpreter initialized at 0xb96210
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 65535 bytes
mapped 1011972 bytes (988 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xb96210 pid: 41517 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 41517)
spawned uWSGI worker 1 (pid: 41519, cores: 2)
spawned uWSGI worker 2 (pid: 41520, cores: 2)
*** Stats server enabled on 127.0.0.1:9001 fd: 12 ***
*** Starting uWSGI 2.0.18 (64bit) on [Wed Jul 17 13:28:03 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 17 July 2019 03:11:56
os: Linux-3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017
nodename: w2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /
writing pidfile to /root/mysite/uwsgi.pid
detected binary path: /usr/local/python356/bin/uwsgi
setuid() to 997
chdir() to /root/mysite
your processes number limit is 3818
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9090).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.18 (64bit) on [Wed Jul 17 13:31:23 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 17 July 2019 03:11:56
os: Linux-3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017
nodename: w2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /
writing pidfile to /root/mysite/uwsgi.pid
detected binary path: /usr/local/python356/bin/uwsgi
setuid() to 997
chdir() to /root/mysite
your processes number limit is 3818
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9090).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.18 (64bit) on [Wed Jul 17 13:31:26 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 17 July 2019 03:11:56
os: Linux-3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017
nodename: w2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /
writing pidfile to /root/mysite/uwsgi.pid
detected binary path: /usr/local/python356/bin/uwsgi
setuid() to 997
chdir() to /root/mysite
your processes number limit is 3818
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:9090).
bind(): Address already in use [core/socket.c line 769]
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/mysite
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:9090)
running /usr/local/python356/bin/uwsgi
[uWSGI] getting INI configuration from /root/mysite/uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed Jul 17 05:32:15 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 17 July 2019 03:11:56
os: Linux-3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017
nodename: w2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/mysite
detected binary path: /usr/local/python356/bin/uwsgi
chdir() to /root/mysite
your processes number limit is 3818
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:9090 fd 3
Python version: 3.6.5 (default, Jul 17 2019, 10:07:53)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Python main interpreter initialized at 0xe916d0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 65535 bytes
mapped 1011972 bytes (988 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xe916d0 pid: 41517 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 41517)
spawned uWSGI worker 1 (pid: 41605, cores: 2)
spawned uWSGI worker 2 (pid: 41606, cores: 2)
*** Stats server enabled on 127.0.0.1:9001 fd: 12 ***
Wed Jul 17 05:32:26 2019 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Jul 17 05:32:26 2019 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Jul 17 05:32:26 2019 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Jul 17 05:32:26 2019 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Wed Jul 17 13:37:26 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 17 July 2019 03:11:56
os: Linux-3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017
nodename: w2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /
writing pidfile to /root/mysite/uwsgi.pid
detected binary path: /usr/local/python356/bin/uwsgi
setuid() to 997
chdir() to /root/mysite
your processes number limit is 3818
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
Python version: 3.6.5 (default, Jul 17 2019, 10:07:53)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Python main interpreter initialized at 0x155d670
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "./mysite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/python356/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/python356/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/python356/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/python356/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/python356/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/python356/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/python356/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/python356/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 66, in <module>
    check_sqlite_version()
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 63, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 41654)
spawned uWSGI worker 1 (pid: 41656, cores: 2)
spawned uWSGI worker 2 (pid: 41657, cores: 2)
*** Stats server enabled on 127.0.0.1:9001 fd: 12 ***
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (64bit) on [Wed Jul 17 13:39:40 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 17 July 2019 03:11:56
os: Linux-3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017
nodename: w2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /
writing pidfile to /root/mysite/uwsgi.pid
detected binary path: /usr/local/python356/bin/uwsgi
setuid() to 997
chdir() to /root/mysite
your processes number limit is 3818
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9090 fd 3
Python version: 3.6.5 (default, Jul 17 2019, 10:07:53)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Python main interpreter initialized at 0x14b8670
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "./mysite/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/python356/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/python356/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/python356/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/python356/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/python356/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/python356/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/python356/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/local/python356/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 66, in <module>
    check_sqlite_version()
  File "/usr/local/python356/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 63, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 41682)
spawned uWSGI worker 1 (pid: 41684, cores: 2)
spawned uWSGI worker 2 (pid: 41685, cores: 2)
*** Stats server enabled on 127.0.0.1:9001 fd: 12 ***
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
goodbye to uWSGI.
